Add grpc-web support
stackb/rules_proto pull request #252
Opened 2022-06-12 03:15 UTC by heartless-clown

Initial grpc-web support with updated examples and readme.
Additionally allows to use executable proto dependencies without wrappers.

2022-06-13 02:50 UTC, pcj commented
This looks good, nice figuring things out in a new repo!  A few nits, but otherwise looks ready to merge soon.

2022-06-13 02:50 UTC, pcj requested changes

2022-06-13 02:50 UTC, pcj commented on pkg/rule/rules_nodejs/grpc_web_js_library.go
> +// grpcWebJsLibrary implements LanguageRule for the 'grpc_web_js_library' rule from @rules_proto.
Comment needs updating

2022-06-13 02:50 UTC, pcj commented on pkg/rule/rules_nodejs/grpc_web_js_library.go
> +		Name:    "@build_stack_rules_proto//rules/nodejs:grpc_web_js_library.bzl",
the directory `rules/nodejs` implies that the rule implementation is related to `bazelbuild/rules_nodejs`...  is it?

2022-06-13 02:50 UTC, pcj commented on plugin/grpc/grpc-web/BUILD.bazel
> +        "@bazel_tools//src/conditions:darwin_x86_64": "@com_github_grpc_grpc_web_releases_download_v1_3_1_protoc_gen_grpc_web_1_3_1_darwin_x86_64//file",
is there a darwin_amd64 option?

2022-06-13 02:50 UTC, pcj commented on pkg/rule/rules_nodejs/grpc_web_js_library.go
> +		Name:    "@build_stack_rules_proto//rules/nodejs:grpc_web_js_library.bzl",
edit: looks like it is: `load("@build_bazel_rules_nodejs//:index.bzl", "js_library")`

2022-06-13 22:06 UTC, pcj commented on pkg/rule/rules_nodejs/grpc_web_js_library.go
> +// grpcWebJsLibrary implements LanguageRule for the 'grpc_web_js_library' rule from @rules_proto.
`from @rules_proto`

2022-06-13 23:07 UTC, heartless-clown commented
The CI should be happy now, and hopefully you satisfied with more clear comments in 
[pkg/rule/rules_nodejs/grpc_web_js_library.go](https://github.com/stackb/rules_proto/pull/252/commits/5352aaf306ff87d3e15431c999dc80621da364e4#diff-57a8f064668c061f091c64f8d2b8b440237645fac69af51ea0504c4bec1c686b)

2022-06-14 13:36 UTC, pcj approved these changes

2022-06-14 13:37 UTC, pcj commented
Thanks @heartless-clown, merging this.

2022-06-14 13:37 UTC, merged