Add grpc-gateway support
stackb/rules_proto pull request #258
Opened 2022-06-14 18:30 UTC by heartless-clown

Adds support for protoc-gen-grpc-gateway and protoc-gen-grpc-openapiv2 plugins.
Sorry, I accidentally closed #253...

2022-06-14 19:11 UTC, pcj requested changes
Small change request, otherwise looking good.

2022-06-14 19:11 UTC, pcj commented on pkg/plugin/grpcecosystem/grpcgateway/protoc-gen-grpc-openapiv2.go
> +	for _, f := range lib.Files() {
Can replace with utility function `protoc.HasServices(lib.Files()...)`

2022-06-14 19:27 UTC, heartless-clown commented on pkg/plugin/grpcecosystem/grpcgateway/protoc-gen-grpc-openapiv2.go
> +	for _, f := range lib.Files() {
Done.

2022-06-14 19:40 UTC, heartless-clown commented
Also, it's beyond me what is wrong with the test targets 
- `//example/golden:grpc_gateway_test`
- `//example/golden:grpc_openapiv2_test`

2022-06-15 06:02 UTC, pcj commented
CI: https://buildkite.com/bazel/stackb-rules-proto/builds?branch=heartless-clown%3Agrpc-gateway

2022-06-15 06:08 UTC, pcj requested changes
Are the `.idea/` files really needed?  Please add this to .gitignore.

2022-06-15 06:49 UTC, heartless-clown commented
CI finally green, `.idea/` removed.

2022-06-15 07:19 UTC, pcj commented
IIRC the reason I left the go language out of the example/{person,place,thing}` is that to do it properly one really needs to compile the well-known types from source rather than relying on precompiled files from something like https://github.com/googleapis/go-genproto, which is how the builtin gazelle proto extension hardcodes it (https://github.com/bazelbuild/bazel-gazelle/blob/master/language/proto/known_go_imports.go).

This is suboptimal because those precompiled files were likely generated by a compiler and proto source configuration different than the one being targeted.

This is what the `proto_repository` and `proto_gazelle` rules allow one to do.  Here's the diff of what that looks like:

```diff
diff --git a/BUILD.bazel b/BUILD.bazel
index c9cf7993..22f98437 100644
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -1,5 +1,6 @@
 load("@bazel_gazelle//:def.bzl", "gazelle", "gazelle_binary")
 load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier")
+load("//rules:proto_gazelle.bzl", "proto_gazelle")
 
 # ----------------------------------------------------
 # Buildifier
@@ -27,9 +28,13 @@ gazelle_binary(
     visibility = ["//visibility:public"],
 )
 
-gazelle(
+proto_gazelle(
     name = "gazelle",
+    cfgs = ["//example:config.yaml"],
     gazelle = ":gazelle-protobuf",
+    imports = [
+        "@protobufapis//:imports.csv",
+    ],
 )
 
 gazelle(
diff --git a/Makefile b/Makefile
index 14b8f6b7..6f091775 100644
--- a/Makefile
+++ b/Makefile
@@ -23,5 +23,4 @@ site:
 
 .PHONY: test
 test:
-	$(BAZEL) test //example/... //pkg/... //plugin/... //language/... //rules/... //toolchain/... \
-		--deleted_packages=//plugin/grpc-ecosystem/grpc-gateway
+	$(BAZEL) test //example/... //pkg/... //plugin/... //language/... //rules/... //toolchain/...
diff --git a/WORKSPACE b/WORKSPACE
index 214a9ca0..35219592 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -237,3 +237,11 @@ load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories")
 node_repositories()
 
 register_toolchains("//toolchain:nodejs")
+
+# ----------------------------------------------------
+# proto_repository rules
+# ----------------------------------------------------
+
+load("//deps:proto_repositories.bzl", "proto_repositories")
+
+proto_repositories()
diff --git a/deps/proto_repositories.bzl b/deps/proto_repositories.bzl
new file mode 100644
index 00000000..dd5bb108
--- /dev/null
+++ b/deps/proto_repositories.bzl
@@ -0,0 +1,76 @@
+"""
+Third-party proto dependencies
+"""
+
+load("@build_stack_rules_proto//rules/proto:proto_repository.bzl", "proto_repository")
+
+# buildifier: disable=function-docstring-header
+def proto_repositories():
+    proto_repository(
+        name = "protobufapis",
+        build_directives = [
+            "gazelle:proto_language go enable true",
+            "gazelle:exclude google/protobuf/compiler/ruby/**",
+            "gazelle:exclude google/protobuf/compiler/cpp/**",
+            "gazelle:exclude google/protobuf/util/**",
+            "gazelle:exclude google/protobuf/unittest/**",
+        ],
+        deleted_files = [
+            "google/protobuf/any_test.proto",
+            "google/protobuf/map_lite_unittest.proto",
+            "google/protobuf/map_proto2_unittest.proto",
+            "google/protobuf/map_unittest.proto",
+            "google/protobuf/test_messages_proto2.proto",
+            "google/protobuf/test_messages_proto3.proto",
+            "google/protobuf/unittest_arena.proto",
+            "google/protobuf/unittest_custom_options.proto",
+            "google/protobuf/unittest_drop_unknown_fields.proto",
+            "google/protobuf/unittest_embed_optimize_for.proto",
+            "google/protobuf/unittest_empty.proto",
+            "google/protobuf/unittest_enormous_descriptor.proto",
+            "google/protobuf/unittest_import_lite.proto",
+            "google/protobuf/unittest_import_public_lite.proto",
+            "google/protobuf/unittest_import_public.proto",
+            "google/protobuf/unittest_import.proto",
+            "google/protobuf/unittest_lazy_dependencies_custom_option.proto",
+            "google/protobuf/unittest_lazy_dependencies_enum.proto",
+            "google/protobuf/unittest_lazy_dependencies.proto",
+            "google/protobuf/unittest_lite_imports_nonlite.proto",
+            "google/protobuf/unittest_lite.proto",
+            "google/protobuf/unittest_mset_wire_format.proto",
+            "google/protobuf/unittest_mset.proto",
+            "google/protobuf/unittest_no_field_presence.proto",
+            "google/protobuf/unittest_no_generic_services.proto",
+            "google/protobuf/unittest_optimize_for.proto",
+            "google/protobuf/unittest_preserve_unknown_enum.proto",
+            "google/protobuf/unittest_preserve_unknown_enum2.proto",
+            "google/protobuf/unittest_proto3_arena_lite.proto",
+            "google/protobuf/unittest_proto3_arena.proto",
+            "google/protobuf/unittest_proto3_lite.proto",
+            "google/protobuf/unittest_proto3_optional.proto",
+            "google/protobuf/unittest_proto3.proto",
+            "google/protobuf/unittest_well_known_types.proto",
+            "google/protobuf/unittest.proto",
+        ],
+        build_file_expunge = True,
+        build_file_proto_mode = "file",
+        cfgs = ["//example:config.yaml"],
+        sha256 = "bf0e5070b4b99240183b29df78155eee335885e53a8af8683964579c214ad301",
+        strip_prefix = "protobuf-3.14.0/src",
+        urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.14.0.zip"],
+    )
+
+    proto_repository(
+        name = "googleapis",
+        build_directives = [
+            "gazelle:proto_language go enable true",
+        ],
+        build_file_generation = "on",
+        build_file_proto_mode = "file",
+        cfgs = ["//example:config.yaml"],
+        override_go_googleapis = True,
+        sha256 = "b9dbc65ebc738a486265ef7b708e9449bf361541890091983e946557ee0a4bfc",
+        strip_prefix = "googleapis-66759bdf6a5ebb898c2a51c8649aefd1ee0b7ffe",
+        type = "zip",
+        urls = ["https://codeload.github.com/googleapis/googleapis/zip/66759bdf6a5ebb898c2a51c8649aefd1ee0b7ffe"],
+    )
diff --git a/example/BUILD.bazel b/example/BUILD.bazel
index 321afa3f..eb65b969 100644
--- a/example/BUILD.bazel
+++ b/example/BUILD.bazel
@@ -164,3 +164,5 @@
 # gazelle:proto_language node_js rule proto_nodejs_library
 # gazelle:proto_language node_js rule grpc_nodejs_library
 # gazelle:proto_language node_js rule grpc_web_js_library
+
+exports_files(["config.yaml"])
diff --git a/example/config.yaml b/example/config.yaml
index 963d6ffe..4c937ab6 100644
--- a/example/config.yaml
+++ b/example/config.yaml
@@ -13,9 +13,9 @@ plugins:
   - name: protoc-gen-go-grpc
     implementation: grpc:grpc-go:protoc-gen-go-grpc
     deps:
-      - "@org_golang_google_grpc//:go_default_library",
-      - "@org_golang_google_grpc//codes",
-      - "@org_golang_google_grpc//status",
+      - "@org_golang_google_grpc//:go_default_library"
+      - "@org_golang_google_grpc//codes"
+      - "@org_golang_google_grpc//status"
 rules:
   - name: proto_compile
     implementation: stackb:rules_proto:proto_compile
@@ -38,9 +38,6 @@ rules:
     implementation: stackb:rules_proto:proto_go_library
     visibility:
       -  //visibility:public
-    resolves:
-      - "google/protobuf/([a-z]+).proto @org_golang_google_protobuf//types/known/${1}pb"
-      - "google/protobuf/(descriptor|plugin).proto @org_golang_google_protobuf//types/${1}pb"
 languages:
   - name: cpp
     plugins:
diff --git a/example/person/BUILD.bazel b/example/person/BUILD.bazel
index 743afd35..caf87e80 100644
--- a/example/person/BUILD.bazel
+++ b/example/person/BUILD.bazel
@@ -43,6 +43,7 @@ proto_compile(
     outputs = ["person.js"],
     plugins = ["@build_stack_rules_proto//plugin/builtin:closurejs"],
     proto = "person_proto",
+    visibility = ["//visibility:public"],
 )
 
 proto_cc_library(
@@ -64,6 +65,7 @@ proto_compile(
     [...]

2022-06-17 12:24 UTC, heartless-clown commented
I'd prefer making a separate PR for utilizing `//rules/proto:proto_repository.bzl` internally.

2024-02-17 22:52 UTC, pcj commented
Closing due to age, but let's re-open if still actively used.

2024-02-17 22:52 UTC, closed without merging